### ISSUE TITLE
Button

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/Git-Conflicts#4]
## Title: Button

Value Proposition

- As a User 
- I want to see a button
- in order to start the quiz

## Description
- QuizCard / Logo / User / Button

## Acceptance criteria

- [ ] QuizCard with title shows up
- [ ] After pushing Button start quiz
- [ ] In the Header User and Logo 

## Tasks:

- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/ User
- [ ] component/ Logo
- [ ] component/Button
- [ ] Write Tests
- [ ] Add to App

**Comment by liebeckm** [comment]
here are my suggestions:
- add wireframe image for better imagination
- component user is maybe something for later?
- also quiz card should only show up **after** you pushed the start button, so this is for later as well?

otherwise fine! :)

**Comment by LuYujin9** [comment]
the Battle Button seems only has a simple function: link to an page. Might be it don't need a component.

**Comment by actyvystom** [comment]
Agree with @liebeckm :) 
Again, either remove components from the wireframe which are not part of your user story or better use a different design to display them in the wireframe.
