### ISSUE TITLE
Card with questions + Timeline + 4 possible answers

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/Git-Conflicts#5]
## Title:

Value Proposition

- As a User
- I want to a list of questions + time line + 4 possible answers
- in order to choose an answer before timeline ends

## Description

- list of questions in QuizCard, add TimeLine, add 4 possible Answers

Acceptance criteria

- [ ] First question appears 
- [ ] In total 3 questions
- [ ] TimeLine expires 
- [ ] 4 possible answer options appears  

## Tasks

- [ ] List the tasks that need to be performed within the dev team
- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/QuizCard
- [ ] component/ Timeline
- [ ] component/ AnswerButton
- [ ] Write Tests
- [ ] fetch random question from db.js
- [ ] create function for timeLine 
- [ ] fetch answers related to question
- [ ] next Button hidden 
- [ ] Add to App

**Comment by alinawinter** [comment]
Looks good to me! :-) Unter Tasks kannst du den ersten Punkt noch rauslöschen

**Comment by actyvystom** [comment]
A nice one! Please see my suggestions:
- Your title does not need to carry all features of card / user story, so you can reduce it to "Card with questions and timeline"
- Agree with @alinawinter: please remove the first task as it is part of your first user story
- Suggestion for your value proposition:

> As a User
I want to see a question, a countdown as a timeline and four possible answer options
to be able to choose an answer before countdown ends

- Your acceptance criteria refers to parts wich are not visible in your wireframe or description ("In total you get 3 questions next to one another"), you should think of an additional user story for these parts
