### ISSUE TITLE
Card with questions + Timeline + 4 possible answers

### ISSUE THREAD

**Issue by Efendi5** [Efendi5/Git-Conflicts#6]
## Title:

Value Proposition

- As a User
- I want to a list of questions + time line + 1 correct answer 3 false answers
- to be able to push next Button after pushing one answer

## Description

![Image](https://user-images.githubusercontent.com/123765768/227486375-b8319052-4b69-4021-8369-70d99566fb12.png)

## Acceptance criteria

- [ ] First question appears 
- [ ] In total 3 questions
- [ ] TimeLine expires 
- [ ] After clicking one answer 
- [ ] the correct/wrong answers are displayed
- [ ] Button for next questions shows up

## Tasks

- [ ] Global Styles
- [ ] component/QuizCard
- [ ] component/ Timeline
- [ ] component/ AnswerButton
- [ ] Write Tests
- [ ] fetch random question from db.js
- [ ] create function for timeLine 
- [ ] fetch answers related to question
- [ ] next Button shows up
- [ ] Add to App

**Comment by zamukaev** [comment]
I think that it is a nice work

**Comment by liebeckm** [comment]
okay, here we go 🏓
- in general, I think there is a little too much functionality for one user story (user story should take 1-2 days including testing etc.). You could split it up into **first userstory:** building a question, 4 answers as well as if the answer was true or false and the points below the user also, the "next"-button.
- I think the timeline would be great for a **second user story**. There you should also think about what will happen if the time expires 👍

**Comment by Efendi5** [comment]
@liebeckm 
Thank you for your review
